version: '3'

services:
  redis2:
    image: redis/redis-stack-server
    container_name: local-redis-server
    ports:
       - "6379:6379"

  app:
    build: .
    container_name: local-redis-py-app
    volumes:
      - ./base:/app/base
      - ./data:/app/data
    working_dir: /app/base
    depends_on:
      - redis
    # environment:
    #   - REDIS_URL=redis://redis:6379/0
